name: Run Sitemap Rebuild

on:
  pull_request:
    branches: [ main, stage ]
    paths:
      - 'fstab.yaml'
      - 'helix-query.yaml'
      - 'helix-sitemap.yaml'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - name: Install secondary dependencies
      run: npm install node-fetch@2 dotenv
    - name: Install main dependencies
      run: npm ci
    - name: Run script
      env:
        HELIX_API_KEY: ${{ secrets.HELIX_API_KEY }}
      run: node ./test/helpers/sitemap.js
