name: Tests and Linting
on:
  push:
    branches: [ "main", "stage" ]
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches: [ "main", "stage" ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install XVFB
        run: sudo apt-get install xvfb

      - name: Install dependencies
        run: npm ci

      - name: Run linters
        run: npm run lint

      - name: Run the tests
        run: xvfb-run -a npm test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage/lcov.info
